### ISSUE TITLE
VipsForeignLoad: file not found

### ISSUE THREAD

**Issue by aricooperdavis** [kmartinez/rti#1]
Hi kmartinez,

I'm having a bit of a play with your PTMfit application (as I have some 20M pixel images that are causing PTMfitter to throw a memory allocation error) and I've run into some trouble.

I am calling PTMfit, which is at `C:\Users\Ari\Downloads\ptmfit\ptmfit.exe` like so:

`.\ptmfit -b 0 -i D:\08.03.17_perspective_corrected\Builds\E3\assembly-files\E3.lp -o E3.ptm`

But I'm getting:

`Reading images:  1terminate called after throwing an instance of 'vips::VError' what():  VipsForeignLoad: file "IMG_0401_corrected_2a.JPG" not found`

So I've inspected my E3.lp file to see where it's pointing to, and it looks a bit like:

```
80
D:\08.03.17_perspective_corrected\Builds\E3\jpeg-exports\IMG_0401_corrected_2a.JPG 0.25402576 0.96320426 0.08779766
D:\08.03.17_perspective_corrected\Builds\E3\jpeg-exports\IMG_0402_corrected_2a.JPG 0.5020512 0.86259 0.062314883
D:\08.03.17_perspective_corrected\Builds\E3\jpeg-exports\IMG_0403_corrected_2a.JPG 0.7281778 0.6851914 0.016426712
...
```

My issue is that each of those file paths are correct:

![Image of "properties" tab illustrating correct file path](https://i.imgur.com/jISZtKK.png)

Can you shed some light on the issue?

Thanks for your help,
Ari

**Comment by kmartinez** [comment]
Hi - sorry its not documented that well - but you need to have the "conventional" directory tree and before running ptmfit.exe change directory into the dir with the images in - normally jpeg-exports
I just did a test on a superdome set with that binary on my windows 10 desktop:
c:\bin\ptmfit\ptmfit.exe -i ..\assembly-files\ball.lp -o ..\finished-files\ball.ptm
and it ran OK (in 39s on 128 7360x4912 pixel images)
I hope that fixes your problem.

To save messing around in cmd window try Phil's RTI Processor:
https://custom-imaging.co.uk/software/
as you just point that to the lp file, ptm fitter location and the TOP of the tree 
(ie D:\08.03.17_perspective_corrected\Builds\E3  for you)
and it does it all for you...

cheers
Kirk

**Comment by aricooperdavis** [comment]
Hi Kirk,
Thanks for your quick response - that's all working now.
Great improvement on the PTMfitter!
All the best,
Ari
