### ISSUE TITLE
ptmfit can't find jpg file

### ISSUE THREAD

**Issue by leszekmp** [kmartinez/rti#2]
I have just tried ptmfit for the first time (on a Windows 64-bit machine), and am having problems getting it to work. I get the following error message:

Reading images:  1terminate called after throwing an instance of 'vips::VError'
  what():  VipsForeignLoad: file "1m_DEM_12_0_z_1.0.jpg"" not found

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

I have checked the path in the lp file multiple times, and it is correct. Here's an example:

C:\Users\leszekp\Desktop\Cahal_Pech\RTI_DEMs\1m_DEM_RTI_DEM\jpeg-exports\1m_DEM_12_0_z_1.0.jpg

If I paste the above path into the path box in a Windows folder, the image displays, so the path must be correct. I've tried putting quotation marks around the path, changing the backslash to a forward slash, and putting the ptmfit executable and all associated files into the same folder as the lp file - no luck. I have attached the entire lp file I'm using as a text file.
[1m_DEM.txt](https://github.com/kmartinez/rti/files/1800876/1m_DEM.txt)

**Comment by aricooperdavis** [comment]
Are you ensuring that you're inside the jpeg-export directory when you're calling ptmfit? Check out the closed issue on this: https://github.com/kmartinez/rti/issues/1

**Comment by leszekmp** [comment]
Missed that closed issue. Yup, that resolved the problem. Thanks!
